body:
  - type: passwordBox
    attributes:
      name: api_key
      label: 'API Key:'
      defaultValue: ""
      description: API key to use Detect Language API
  - type: dropdown
    attributes:
      name: main_language
      label: "Main Language:"
      defaultValue: English
      options:
        - Bulgarian
        - Czech
        - Danish
        - German
        - Greek
        - English
        - Spanish
        - Estonian
        - Finnish
        - French
        - Hungarian
        - Italian
        - Japan
        - Lithuanian
        - Latvian
        - Maltese
        - Dutch
        - Polish
        - Portuguese
        - Romanian
        - Russian
        - Slovak
        - Swedish
        - Chinese
      description: "The main language to be used"
  - type: dropdown
    attributes:
      name: secondary_language
      label: "Secondary Language:"
      defaultValue: French
      options:
        - Bulgarian
        - Czech
        - Danish
        - German
        - Greek
        - English
        - Spanish
        - Estonian
        - Finnish
        - French
        - Hungarian
        - Italian
        - Japan
        - Lithuanian
        - Latvian
        - Maltese
        - Dutch
        - Polish
        - Portuguese
        - Romanian
        - Russian
        - Slovak
        - Swedish
        - Chinese
      description: "The second language to be used"
  - type: checkbox
    attributes:
      name: show_less_common_translation
      label: 'Show less common translation: '
      defaultValue: True
      description: "When enabled, the less common translation are displayed"

